/**
 * Tailwind build config — replaces the Play-CDN runtime (cdn.tailwindcss.com)
 * with a precompiled static stylesheet for much faster mobile loads.
 *
 * The `content` globs are scanned for class names, so every Tailwind class used
 * as a literal string in index.html or app.js is included. (There are no
 * fragment-concatenated class names like "grid-cols-" + n in the codebase.)
 *
 * theme.extend mirrors the former runtime `tailwind.config` in index.html.
 * Generated by the Docker build step (npm run build:css); also checked in.
 */
module.exports = {
	content: ["./index.html", "./app.js", "./excalidraw-embed.html"],
	theme: {
		extend: {
			fontFamily: {
				sans: [
					"ui-sans-serif",
					"system-ui",
					"-apple-system",
					"Segoe UI",
					"Roboto",
					"Inter",
					"Arial",
					"Noto Sans",
					"sans-serif",
				],
			},
			boxShadow: {
				soft: "0 10px 30px rgba(0,0,0,.25)",
			},
		},
	},
};
